Add the following changes:
- Add some git shortcuts
- alertme function in bashrc
- Move whiz logic out of bash
- Don't know why a bunch of stuff changed but it's probably a weird
  encoding thing

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -11,7 +11,10 @@ source ~/.cargo/env
 export PATH=$PATH:~/.local/bin # add .local/bin to path
 export HISTSIZE="" # linux: infinite history
 export RIPGREP_CONFIG_PATH="$HOME/.rgrc"
-source ~/.bash_secrets
+sauce() {
+  source ~/.bash_secrets
+}
+sauce
 
 # ============================================================================
 # Environment Settings
@@ -48,7 +51,9 @@ alias gdcn="git diff --cached --name-only"
 alias gst="git stash"
 alias gsta="git stash apply"
 alias gstd="git stash drop"
+alias gr="git restore"
 alias gri="git rebase -i"
+alias grs="git restore --staged"
 alias gpsuo="git push --set-upstream origin"
 alias cmake="/Applications/CMake.app/Contents/bin/cmake"
 gdh() {
@@ -171,43 +176,23 @@ alias please="sudo"
 alias ":q"="exit"
 
 # ============================================================================
+# Command to play an appropriate jingle depending on the exit code was
+# ============================================================================
+alertme() {
+    local EXIT="$?"
+    silly_notify "$EXIT"
+}
+
+# ============================================================================
 # Bookmark Functions - whiz (whiz, as in "whiz to $bookmarkname")
 # ============================================================================
 # Go to Bookmark
 whiz () {
     local bookmark_name="$1"
-    if [ "$bookmark_name" == "help" ]; then
-        zmansynopsis whiz
-    elif [ -n "$bookmark_name" ]; then
-        local bookmark_line=$(grep "$bookmark_name " ~/.NERDTreeBookmarks)
-        local destination=${bookmark_line/$bookmark_name \~//home/zachtaira}
-        local final_destination=${destination/$bookmark_name /}
-        echo "Whizzing to $final_destination"
-        cd $final_destination
-    else
-        echo ""
-        echo "Here are the bookmarks you can currently whiz to:"
-        nyan ~/.NERDTreeBookmarks 20
-        echo ""
-    fi
-}
-
-# Open folder at Bookmark
-whizo () {
-    local bookmark_name="$1"
-    if [ "$bookmark_name" == "help" ]; then
-        zmansynopsis whiz
-    elif [ -n "$bookmark_name" ]; then
-        local bookmark_line=$(grep "$bookmark_name " ~/.NERDTreeBookmarks)
-        local destination=${bookmark_line/$bookmark_name \~//home/zachtaira}
-        local final_destination=${destination/$bookmark_name /}
-        echo "Whizzing to $final_destination"
-        xdg-open "$final_destination"
-    else
-        echo ""
-        echo "Here are the bookmarks you can currently whiz to:"
-        nyan ~/.NERDTreeBookmarks 20
-        echo ""
+    if [ "${bookmark_name}" == "" ]; then
+        whiz_plumbing
+    elif [ -n "${bookmark_name}" ]; then
+        cd $(whiz_plumbing -b "${bookmark_name}")
     fi
 }
 
@@ -220,20 +205,6 @@ whizadd () {
     else
         zmansynopsis whizadd
     fi
-}
-
-# Read in lines and space them.
-# It's a spaced version of cat.
-nyan () {
-    local filename="$1"
-    local column_width="$2"
-    while read -r line
-    do
-        local first_word=$(echo $line | sed -e 's/ .*//')
-        local amount_of_spaces=$(($column_width-${#first_word}))
-        local spaces=$(printf "%0.s." $(seq 1 $amount_of_spaces))
-        echo $(printf '%s' "$line" | sed -e "s/ /$spaces/")
-    done < "$filename"
 }
 
 # ============================================================================
